# Runs when a Pull Request is opened (to check code before review or merge).
name: PR Opened

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  pull_request:
    types: [opened]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps: 
    - name: Echo message
      run: |
        echo "📂 Workflow triggered: Pull Request opened"

