# Runs when new commits are pushed to an open Pull Request (to re-check updated code).
name: PR Synchronize

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  pull_request:
    types: [synchronize]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps: 
    - name: Echo message
      run: |
        echo "🔄 Workflow triggered: Pull Request synchronized"
